### PR TITLE
Actually make the beatmap editor screen this time

### PR DESCRIPTION
**Pull request by ebay-kid**

### CODE REVIEW

**Comment by ebay-kid** [comment]
@stanleymw we were discussing potentially merging this to keep both our branches in line with each other. If you'd like to merge I've resolved the merge conflicts with main and the code is in a non-crashing state.

**Comment by ebay-kid** [comment]
If you are planning to merge, please complete https://github.com/stanleymw/lovey/tree/next with a complete class definition of `Beatmap.java` so I have something to cross-reference while writing the beatmap creator screen.

**Comment by stanleymw** [comment]
I believe the current `Beatmap.java` implementation in your branch is complete.  It looks like the only thing necessary to change is the spawn record (I added a time field to indicate the amount of time it will take for the spawnable to reach the dome, so that the game will ensure that the target touches the dome at `spawnTime + time` seconds into the game).

I also temporarily changed the InteractableSpawner.java class to include a temporary constructor that allows me to quickly make a beatmap for development purposes/testing the spawning mechanics. This does not need to be included when the beatmap editor is finished.

**Comment by ebay-kid** [comment]
Merging as requested.

**Pull request merged**
